# Generated by Django 5.1.4 on 2025-03-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_codesnippet_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='desc',
            field=models.CharField(blank=True, default='No description provided', max_length=1000, null=True),
        ),
    ]
